name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - name: Get dependencies
        run: flutter pub get
      - name: Run analyze 🔬
        run: flutter analyze
      - name: Run tests 🥽
        run: flutter test
